Specify decommissioning guidance
18F/tts-tech-portfolio pull request #1503
Opened 2021-07-30 16:01 UTC by dylanirlbeck

Fixes #1501

2021-08-04 15:49 UTC, afeld requested changes
Left a bunch of nitpicky comments 😄 While you're in there, mind switching to soft wrapping?

https://github.com/18F/tts-tech-portfolio/pull/1476/files#r675751646

2021-08-04 15:49 UTC, afeld commented on .github/ISSUE_TEMPLATE/decommission.md
> +about: Checklist for shutting down a system (website, micro/informational site,
Slightly simpler.

```suggestion
about: Checklist for shutting down a site/system/app
```

2021-08-04 15:49 UTC, afeld commented on .github/ISSUE_TEMPLATE/decommission.md
> +`https://login.gov`. This checklist also applies when decommissioning a site and merging its content
```suggestion
This checklist also applies when decommissioning a site and merging its content
```

2021-08-04 15:49 UTC, afeld commented on .github/ISSUE_TEMPLATE/decommission.md
> +include micro/informational sites on Federalist such as `https://search.gov` and
I worry that will confuse folks, since those sites are parts of systems that _do_ have backends. Don't feel strongly though.

```suggestion
include micro/informational sites on Federalist.
```

2021-08-04 15:49 UTC, afeld commented on .github/ISSUE_TEMPLATE/decommission.md
> +  decommissioned, archived, or redirected ([example](https://github.com/18F/before-you-ship#readme))
README better than the description? (I don't feel strongly.)

2021-08-04 15:49 UTC, afeld commented on .github/ISSUE_TEMPLATE/decommission.md
> +    - [ ] New Relic - [#admins-newrelic](https://gsa-tts.slack.com/messages/admins-newrelic)
This likely won't apply to sites without backends.

2021-08-04 15:49 UTC, afeld commented on .github/ISSUE_TEMPLATE/decommission.md
> +- [ ] (If applicable) Ask the Tech Portfolio to update [TTS subdomains](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=1884617968)
```suggestion
- [ ] (If a second-level domain) Ask the Tech Portfolio to update the [list of TTS domains](https://docs.google.com/spreadsheets/d/12pfcEIEXaJTjIKex-3wnI89erIvgKf9B_XpGkDl6qsM/edit#gid=824448842)
```

2021-08-04 15:49 UTC, afeld commented on .github/ISSUE_TEMPLATE/decommission.md
> +> [Helpful resource about sites vs systems](https://docs.google.com/document/d/1chNbOfxs2vLGSUuIPtWZregaUeT-ruLc8EufEzt9GZk/edit)
```suggestion
> [Helpful resource about sites vs systems.](https://docs.google.com/document/d/1chNbOfxs2vLGSUuIPtWZregaUeT-ruLc8EufEzt9GZk/edit) Feel free to delete checklist items that aren't applicable.
```

2021-08-04 15:49 UTC, afeld commented on .github/ISSUE_TEMPLATE/decommission.md
>  - [ ] Export any relevant [records](https://handbook.tts.gsa.gov/records-management/) and store in Google Drive.
```suggestion
- [ ] Export any relevant [records](https://handbook.tts.gsa.gov/records-management/) and store in GitHub or Google Drive.
```

2021-08-04 15:49 UTC, afeld commented on .github/ISSUE_TEMPLATE/decommission.md
> +- [ ] [Update the TouchPoints record](https://touchpoints.app.cloud.gov/admin/websites)
cc https://github.com/GSA/touchpoints/issues/585

2021-08-04 15:49 UTC, afeld commented on .github/ISSUE_TEMPLATE/decommission.md
> +  - [ ] Production status is updated to 'Redirect'
Ideally we could defer to instructions within Touchpoints about what the different statuses mean so that it's consistent across all entries in there, but not a big deal. cc @ryanwoldatwork

2021-08-04 15:49 UTC, afeld commented on .github/ISSUE_TEMPLATE/decommission.md
>  - [ ] Domain changes
This applies to all sites.

2021-08-04 15:49 UTC, afeld commented on .github/ISSUE_TEMPLATE/decommission.md
>  - [ ] Notify other parts of GSA
@sfrederick-gsa-gov Any special notification that needs to be done when taking down a Federalist site?

2021-08-05 15:48 UTC, dylanirlbeck commented on .github/ISSUE_TEMPLATE/decommission.md
> +  decommissioned, archived, or redirected ([example](https://github.com/18F/before-you-ship#readme))
I'm going to say yes. As a matter of preference, I would rather have the description stay true to what the repo's use was and the README be used to describe status updates (e.g. archival).

2021-08-05 15:49 UTC, dylanirlbeck commented on .github/ISSUE_TEMPLATE/decommission.md
> +    - [ ] New Relic - [#admins-newrelic](https://gsa-tts.slack.com/messages/admins-newrelic)
(I'm going to assume you just meant the box for New Relic, not the others -- correct me if I'm wrong.)

2021-08-05 15:51 UTC, dylanirlbeck commented on .github/ISSUE_TEMPLATE/decommission.md
> +- [ ] [Update the TouchPoints record](https://touchpoints.app.cloud.gov/admin/websites)
This. I did not prefer having to go to Ryan the couple times I needed to update the before-you-ship record (since I wasn't the designated site owner).

2021-08-05 17:58 UTC, dylanirlbeck commented
@afeld I see you left a few questions for others, but I'll ping you for a re-review for everything else. I'm happy to wait to merge until the others respond but I don't think that blocks another review.

2021-08-06 16:24 UTC, afeld approved these changes

2021-08-06 16:26 UTC, merged