Add an offboarding checklist
18F/tts-tech-portfolio pull request #1551
Opened 2021-08-26 22:39 UTC by rocheller123

Added tasks to offboard a departing Tech Portfolio member based on the tasks from Onboarding checklist (https://github.com/18F/tts-tech-portfolio/blob/main/.github/ISSUE_TEMPLATE/onboarding.md)

2021-08-30 17:50 UTC, afeld reviewed
Hesitant to merge this since we then need to keep the mirrored onboarding/offboarding checklists in sync. Thoughts?

2021-09-10 14:52 UTC, JJediny requested changes
Two asks

2021-09-10 14:52 UTC, JJediny commented on .github/ISSUE_TEMPLATE/offboarding.md
> +# Onboarding Process
@rocheller123 did you mean for this to update the onboarding.md template?

2021-09-10 14:52 UTC, JJediny commented on .github/ISSUE_TEMPLATE/offboarding.md
> +| Name | About | Title | Labels | Assignees |
@rocheller123 was this yaml frontmatter changed to a markdown table by mistake? issue templates need to be in yaml

2021-09-10 15:41 UTC, rocheller123 commented on .github/ISSUE_TEMPLATE/offboarding.md
> +| Name | About | Title | Labels | Assignees |
@JJediny It was a mistake. I will change it back.

2021-09-13 20:28 UTC, rocheller123 commented on .github/ISSUE_TEMPLATE/offboarding.md
> +# Onboarding Process
@JJediny the offboarding template would be the canonical source for the checklist to offboard and onboard Tech Portfolio members since a checklist to offboard a member is more important for security reasons than onboarding.

2021-09-17 23:27 UTC, adborden approved these changes
Looks like a good compromise between having the list in one place but still having clear instructions.

One minor comment: the team_access.md doesn't make sense under the `ISSUE_TEMPLATE` directory unless you want it to show up as a new option under [New Issues](https://github.com/18F/tts-tech-portfolio/issues/new/choose). Maybe just have it be a section at the bottom of `how_we_work/offboarding.md`?

2021-09-29 23:40 UTC, adborden approved these changes

2021-11-12 17:30 UTC, JJediny approved these changes
lgtm lets merge

2021-11-12 17:30 UTC, merged