Add instructions for Tech Portfolio steps for CSP account and user creation
18F/tts-tech-portfolio pull request #1567
Opened 2021-09-09 15:10 UTC by JJediny

All the specific steps for each CSP will be made into their own issue templates

2021-09-22 23:10 UTC, adborden requested changes
Let's make sure this is part of the onboarding checklist, otherwise this seems like team members won't be notified of new requests.

How about this lives in the TTS Handbook? Similar to how we administer any other tool, I think having admin docs side-by-side with user docs is helpful and more visible. Docs in this repo feel buried to me.

2021-09-22 23:10 UTC, adborden commented on how_we_work/account_management/cloud-service-providers.md
> +Tech Portfolio members should sign up for notifications to changes in the sheet.
This should be part of the onboarding checklist.

2021-09-22 23:10 UTC, adborden commented on how_we_work/account_management/cloud-service-providers.md
> +When a new request is made the Tech Portfolio should immediately acknowledge the request by reaching out to the requestor via slack, email, or gchat.
Should this be a responsibility for Ops Rotation?

2022-04-28 13:40 UTC, JJediny reviewed
@rocheller123 this is ready for merging need your approval

2022-08-29 14:41 UTC, merged