Create offboarding.md
18F/tts-tech-portfolio pull request #810
Opened 2020-09-02 10:33 UTC by its-a-lisa-at-work

first pass at the offboarding checklist; might not be perfect

2020-10-08 15:10 UTC, its-a-lisa-at-work commented
hmmm, I don't know what I need to do with this..

2020-10-14 14:44 UTC, afeld requested changes

2020-10-14 14:44 UTC, afeld commented on .github/ISSUE_TEMPLATE/offboarding.md
> +- [ ] Remove them to the [@18F/tts-tech-portfolio](https://github.com/orgs/18F/teams/tts-tech-portfolio) team on GitHub.
These would all be taken care of as part of the [general offboarding tasks](https://docs.google.com/spreadsheets/d/1rp8n78tFHqyvvHzsYuBo_XE3Jg1LwOuOX-R9TMRnZI8/edit#gid=1916685737).

```suggestion
```

2020-10-14 14:44 UTC, afeld commented on .github/ISSUE_TEMPLATE/offboarding.md
> +- [ ] Initiate the process via the Leaving TTS Handbook page
```suggestion
- [ ] [Initiate the process](https://handbook.tts.gsa.gov/leaving-tts/)
```

2020-10-19 15:58 UTC, its-a-lisa-at-work commented on .github/ISSUE_TEMPLATE/offboarding.md
> +- [ ] Remove them to the [@18F/tts-tech-portfolio](https://github.com/orgs/18F/teams/tts-tech-portfolio) team on GitHub.
I don't think so... I feel like those are unique to our team, right?

2020-10-19 22:59 UTC, afeld commented on .github/ISSUE_TEMPLATE/offboarding.md
> +- [ ] Remove them to the [@18F/tts-tech-portfolio](https://github.com/orgs/18F/teams/tts-tech-portfolio) team on GitHub.
The general offboarding would make these team-specific offboarding steps irrelevant. For example, [Slack user groups can only contain full members](https://slack.com/help/articles/212906697-Create-a-user-group#create-a-user-group), so someone being converted to a single-channel guest would take care of that step. Ditto for the GitHub team. IaaS account removal is in the [offboarding checklist](https://docs.google.com/spreadsheets/d/1rp8n78tFHqyvvHzsYuBo_XE3Jg1LwOuOX-R9TMRnZI8/edit#gid=1916685737) (just added Azure and Google Cloud), so all set there too.

2020-10-20 13:12 UTC, its-a-lisa-at-work commented on .github/ISSUE_TEMPLATE/offboarding.md
> +- [ ] Remove them to the [@18F/tts-tech-portfolio](https://github.com/orgs/18F/teams/tts-tech-portfolio) team on GitHub.
Ok, got it! I hadn't seen Azure and Google get added to the off-boarding list.

2020-10-20 13:12 UTC, its-a-lisa-at-work reviewed
LGTM (finally :))

2020-10-28 17:21 UTC, its-a-lisa-at-work commented
@afeld if you could figure out this CircleCI error, that would be helpful, I won't be able to get to this until Monday at the earliest (when I have a monitor)

2020-10-28 20:28 UTC, afeld approved these changes
CircleCI error is `No configuration was found in your project`, which just means that this branch is old. Nothing to worry about.

2020-10-28 20:28 UTC, merged