add page on technical standards
18F/tts-tech-portfolio pull request #848
Opened 2020-09-23 20:20 UTC by afeld

These have been floating around my head for a while; figured it made sense to write them down. This is only meant as a starting place; there's probably more we can add, but I would rather have _something_ merged sooner than later. If there's any parts of this folks disagree about, would rather remove that line than let the debate be a blocker.

**Please wait until all reviewers approve before merging.**

2020-09-23 20:22 UTC, afeld commented on how_we_work/standards.md
> +    - [Black](https://black.readthedocs.io/en/stable/) for Python
I actually don't care [which one](https://www.kevinpeters.net/auto-formatters-for-python) we use — anyone have strong feelings?

2020-09-23 20:23 UTC, afeld commented on how_we_work/standards.md
> +- **Continuous integration/deployment:** [CircleCI](https://circleci.com/)
Going with this over GitHub Actions since we have more repositories that use it already; don't have a strong preference.

2020-09-25 17:31 UTC, JJediny requested changes
LGTM - but need to add ref to google filestream for sync functionality

2020-09-25 17:31 UTC, JJediny commented on how_we_work/standards.md
> +
should link to the use of google filestream (availability in JAMF self service?)

2020-10-05 15:14 UTC, JJediny submitted a review, later dismissed
1. allow github actions
2. ref filestream 

happy to contribute a commit if needed

2020-10-05 15:14 UTC, JJediny commented on how_we_work/standards.md
> +- **Continuous integration/deployment:** [CircleCI](https://circleci.com/)
think we should establish an and/or setup with github actions

2020-10-05 22:16 UTC, afeld commented on how_we_work/standards.md
> +- **Continuous integration/deployment:** [CircleCI](https://circleci.com/)
We are already using CircleCI in some places, so listed both as a reflection of the current state. I think consolidating down the road is a good idea.

2020-10-14 21:38 UTC, amitfreeman-gov approved these changes
Makes sense to me - shipit

2020-10-14 21:50 UTC, merged