list the sites the Tech Portfolio is responsible for
18F/tts-tech-portfolio pull request #909
Opened 2020-10-15 20:28 UTC by afeld

2020-10-20 00:14 UTC, afeld commented on how_we_work/sites.md
> +| [Handbook](https://handbook.tts.gsa.gov/)           | [18F/handbook](https://github.com/18F/handbook)                 | Mainly the [software and tools](https://handbook.tts.gsa.gov/#software-and-to
@its-a-lisa-at-work The intention of saying we aren't the Handbook content owners is that not all those issues should show up on our project board. Closing them doesn't quite feel appropriate since the Handbook is a shared resource. Open to ideas.

2020-10-20 13:07 UTC, its-a-lisa-at-work requested changes
This is going in a good direction and think its great that we're starting to continuously update docs!

2020-10-20 13:07 UTC, its-a-lisa-at-work commented on how_we_work/sites.md
> +| [Handbook](https://handbook.tts.gsa.gov/)           | [18F/handbook](https://github.com/18F/handbook)                 | Mainly the [software and tools](https://handbook.tts.gsa.gov/#software-and-to
Maybe we shouldn't try to solve the Handbook problem now and prioritize the issue that is likely to take care of it https://github.com/18F/tts-tech-portfolio/issues/719?

2020-10-20 13:07 UTC, its-a-lisa-at-work commented on how_we_work/sites.md
> +| [Handbook](https://handbook.tts.gsa.gov/)           | [18F/handbook](https://github.com/18F/handbook)                 | Mainly the [software and tools](https://handbook.tts.gsa.gov/#software-and-to
Thoughts about the following for content ownership? 

https://handbook.tts.gsa.gov/tech-portfolio/
https://handbook.tts.gsa.gov/equipment/
https://handbook.tts.gsa.gov/responding-to-public-disclosure-vulnerabilities/
https://handbook.tts.gsa.gov/intro-to-tts-tech-portfolio/

2020-10-23 19:49 UTC, its-a-lisa-at-work commented on how_we_work/sites.md
> +| [Handbook](https://handbook.tts.gsa.gov/)           | [18F/handbook](https://github.com/18F/handbook)                 | Mainly the [software and tools](https://handbook.tts.gsa.gov/#software-and-to
@afeld nudge on question

2020-10-23 19:50 UTC, its-a-lisa-at-work commented on how_we_work/sites.md
> +| [Handbook](https://handbook.tts.gsa.gov/)           | [18F/handbook](https://github.com/18F/handbook)                 | Mainly the [software and tools](https://handbook.tts.gsa.gov/#software-and-to
@afeld @JJediny

2020-10-23 23:29 UTC, afeld commented on how_we_work/sites.md
> +| [Handbook](https://handbook.tts.gsa.gov/)           | [18F/handbook](https://github.com/18F/handbook)                 | Mainly the [software and tools](https://handbook.tts.gsa.gov/#software-and-to
What if it just says "partial" and links to that issue?

2020-10-23 23:31 UTC, afeld commented on how_we_work/sites.md
> +| [Handbook](https://handbook.tts.gsa.gov/)           | [18F/handbook](https://github.com/18F/handbook)                 | Mainly the [software and tools](https://handbook.tts.gsa.gov/#software-and-to
Yep, all examples! Didn't want to go into listing individual pages since it will get out of date quickly. For later: using [GitHub's CODEOWNERS feature](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners).

2020-10-23 23:57 UTC, its-a-lisa-at-work commented
Works for me!

Sent from my iPhone

On Oct 23, 2020, at 7:29 PM, Aidan Feldman <notifications@github.com> wrote:

﻿

*@afeld* commented on this pull request.
------------------------------

In how_we_work/sites.md
<https://github.com/18F/tts-tech-portfolio/pull/909#discussion_r511196347>:

> @@ -0,0 +1,12 @@
+# Sites
+
+The Tech Portfolio is the "technical owner" for the following sites,
meaning we keep them running, fix any security vulnerabilities, etc.
In some cases, we are also responsible for maintaining the content.
+
+| Name                                                | Repository
                                                  | Content owner
                                                                     |
+| --------------------------------------------------- |
--------------------------------------------------------------- |
---------------------------------------------------------------------------------------
|
+| [Before You Ship](https://before-you-ship.18f.gov/) |
[18F/before-you-ship](https://github.com/18F/before-you-ship)   | Y

            |
+| [Chat](https://chat.18f.gov/)                       |
[18F/chat](https://github.com/18F/chat)                         | Y

            |
+| [Handbook](https://handbook.tts.gsa.gov/)           |
[18F/handbook](https://github.com/18F/handbook)                 |
Mainly the [software and
tools](https://handbook.tts.gsa.gov/#software-and-tools) pages |

What if it just says "partial" and links to that issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/18F/tts-tech-portfolio/pull/909#discussion_r511196347>,
or unsubscribe
<https://github.com/notifications/unsubscribe-auth/AHPQBHQGKHTA5WD5ENF7R5TSMIGW5ANCNFSM4SSO4L7Q>
.

2020-10-28 17:25 UTC, its-a-lisa-at-work commented on how_we_work/sites.md
> +| [Handbook](https://handbook.tts.gsa.gov/)           | [18F/handbook](https://github.com/18F/handbook)                 | Mainly the [software and tools](https://handbook.tts.gsa.gov/#software-and-to
better, lets do it!

2020-10-28 17:26 UTC, its-a-lisa-at-work commented on how_we_work/sites.md
> +| [Handbook](https://handbook.tts.gsa.gov/)           | [18F/handbook](https://github.com/18F/handbook)                 | Mainly the [software and tools](https://handbook.tts.gsa.gov/#software-and-to
I mean, I don't think it'd get out of date quickly, creating whole new pages that we own isn't something that is done often or arbitrarily...

2020-10-30 14:59 UTC, its-a-lisa-at-work approved these changes
lgtm

2020-10-30 14:59 UTC, merged