Update to include PIF GitHub repo
18F/tts-tech-portfolio pull request #918
Opened 2020-10-19 18:51 UTC by its-a-lisa-at-work

Make sure that new folks are added to the PIF repo so they can do OpsRotation activity

2020-10-19 22:18 UTC, afeld requested changes

2020-10-19 22:18 UTC, afeld commented on .github/ISSUE_TEMPLATE/onboarding.md
> +- [ ] Add them to the [@presedential-innovation-fellows](https://github.com/orgs/presidential-innovation-fellows/teams/github-admins) team on GitHub.
```suggestion
- [ ] Add them as an Owner on all [TTS-managed GitHub organizations](https://handbook.tts.gsa.gov/github/#organizations).
```

2020-10-20 13:21 UTC, its-a-lisa-at-work commented on .github/ISSUE_TEMPLATE/onboarding.md
> +- [ ] Add them to the [@presedential-innovation-fellows](https://github.com/orgs/presidential-innovation-fellows/teams/github-admins) team on GitHub.
Much improved; but cloud.gov is the exception, correct? I feel like we're not all owners on that on purpose because of the limit of the number of people that can be on Private repos. But I know things might have changed since that originally happened. 

Also, with that being said, I am pretty sure I am not an Owner for all of those repos...

2020-10-23 19:48 UTC, its-a-lisa-at-work commented on .github/ISSUE_TEMPLATE/onboarding.md
> +- [ ] Add them to the [@presedential-innovation-fellows](https://github.com/orgs/presidential-innovation-fellows/teams/github-admins) team on GitHub.
@afeld nudge on my question

2020-10-23 23:37 UTC, afeld commented on .github/ISSUE_TEMPLATE/onboarding.md
> +- [ ] Add them to the [@presedential-innovation-fellows](https://github.com/orgs/presidential-innovation-fellows/teams/github-admins) team on GitHub.
> cloud.gov is the exception, correct?

Mmm. Maybe we change the table in that linked Handbook page to say "Managed by"? Or "where to ask for admin help"?

> I am not an Owner for all of those

Nor am I. https://github.com/18F/tts-tech-portfolio/issues/83

2020-10-28 17:25 UTC, its-a-lisa-at-work commented
closing this and we can revisit once #83 is resolved

2020-10-28 17:25 UTC, closed without merging